### ISSUE TITLE
[Bug] Lots of redundant sim warning events

### ISSUE THREAD

**Issue by kjhambrick** [openrocket/openrocket#2750]
### Describe the bug

Built 2412 - RC1 on 2025-03-11 at 05:54 CST / 11:54 GMT via `git clone` and gradle on Slackware Linux 15.0 ( 64 bit ) with openjdk17-17.0.14_7

When I simulate Stability -vs- Time, there is a lot of noise in the plot during the thrust phase.

Exported Plot below.

EDIT:  I expanded the plot so it only includes boost and early coast.  The noise is actually repeated Mach 1.1 warnings.

New Screenshot attached.

Is there a gradle build log that might help ?

Thanks everybody !

-- kjh

### To Reproduce

1. Build 2412 RC1and start it up
2. Load an existing Model
3. Simulate Stability -vs- Time
...

#### Screenshot(s):
*(drag-and-drop the s

![Image](https://github.com/user-attachments/assets/2e2b8cb5-0bc3-4f7e-961b-73729716a0ef)

![Image](https://github.com/user-attachments/assets/484090f2-85a1-4c3d-8123-5598086a6808)

![Image](https://github.com/user-attachments/assets/a01ac38e-c603-41ed-b04e-5bc90800348a)

[MAUDE-38-1200-loki-md-hed-power-perch-4-x-2.000-span-m2.50-fins-2412-RC01.ork.zip](https://github.com/user-attachments/files/19261130/MAUDE-38-1200-loki-md-hed-power-perch-4-x-2.000-span-m2.50-fins-2412-RC01.ork.zip)

creenshot(s) here)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

24.12 RC1

### What platform are you running on?

Slackware Linux 15.0 with openjdk17-17.0.14_7

### Additional context

I was playing with David Bellhorn's OR Multi-Level Wind https://gpsdriftcast.com/orwind/

But I switched back to Average Wind = 12mph for the plot.

**Comment by JoePfeiffer** [comment]
Is the .ork file you posted the same rocket as the screen shots? There's a lot of internal structure in the .ork file (overlapping the J510 motor) that I don't see in the screen shots.

Regardless, I'll wait for other people's opinions, but I don't think this is a bug. You've got a rocket with a really high longitudinal moment of inertia and relatively small fins; this means the angle of attack is doing quite a bit of oscillation before settling down. Non-zero angle of attack moves the center of pressure forward; see this plot:
![Image](https://github.com/user-attachments/assets/832504aa-640b-4fef-a10e-c1951ee4e985)
(it actually displays the magnitude of the angle of attack, giving the illusion that it's bouncing off 0 instead of oscillating).
As the oscillations die down the stability also settles down.

(you will be happy to know that the most recent unstable has fixed the "zillions of supersonic warnings" bug)

**Comment by kjhambrick** [comment]
Thanks Joe !

Yes, this rocket is pretty long to accomodate a Loki 38-1200 motor so off-axis disturbances ( like the 12mph wind ) will be slow to decay.

But !

I ammended my ticket entry after I saw that the 'noise' was actually a series of Mach 1.1 warning markers :)

I acually expected the wiggles -n- squiggles in the stability -vs- time plot but I didn't understand that the greenish 'noise' was actually a series of warnings.

I'll `git` a new set of source code and build and try it.

Thanks again !!!

-- kjh

**Comment by kjhambrick** [comment]
Joe --

I set aside the old 24.12 RC1 code and reran `gradle clean check build dist`

The internal structure that overlaps the motor that you see in the .ork is due to three variations of an Oatey min diameter motor retainer that I included in the model

![Image](https://github.com/user-attachments/assets/38f18221-0a25-4863-bce3-730bce167f84)

Note that the x-long and long have mass and cg overrides -- they're set to 0.00 and the sub-components override is clicked.

When I open the.ork, I use the new 24.12 feature to hide the Oatey assemblies that don't fit the motor.

Note that only the 'std' Oatey is visible in the screen shot.

I believe that explains the apparent difference between the .ork and the screen shot ?

I still see the Mach 1.1 warnings though:

![Image](https://github.com/user-attachments/assets/b4f4f3fb-0fbb-4613-bbff-34fb185c1097)

Did I download the wrong code via `git clone https://github.com/openrocket/openrocket.git` ?

Or maybe I misunderstood what you were saying about removing the zillions of supersonic warnings ?

Thanks again !

-- kjh

**Comment by JoePfeiffer** [comment]
Try doing a 
git pull
to make sure you're up to date with the repository. Fixing the "multiple warnings" was just last Wednesday.
If you then do a
git log
one of the commits should be

commit b7c0edc0fc0919f5213dd842c91a8700080c2ddd
Merge: 2e8b0c9d1 9f3fa504c
Author: Joe Pfeiffer <joseph@pfeifferfamily.net>
Date:   Wed Mar 12 14:40:37 2025 -0600

    Merge pull request #2746 from JoePfeiffer/open-warnings-again
    
    If a warning isn't actually added to the warning set, don't put a new flight event for it.

Assuming that's in there, recompiling should give you a version that doesn't produce all the extra warnings.

**Comment by kjhambrick** [comment]
Joe --

I did `git pull` and I got:  Already up to date.

So I did `git log |less` and I do see your commit:

``commit b7c0edc0fc0919f5213dd842c91a8700080c2ddd
Merge: 2e8b0c9d1 9f3fa504c
Author: Joe Pfeiffer <joseph@pfeifferfamily.net>
Date:   Wed Mar 12 14:40:37 2025 -0600

    Merge pull request #2746 from JoePfeiffer/open-warnings-again
    
    If a warning isn't actually added to the warning set, don't put a new flight event for it.
``

However I still see all the warnings.

Thoughts ?

-- kjh

**Comment by JoePfeiffer** [comment]
> Thoughts ?
> 
> -- kjh

I'm mystified -- I've got no idea how it can be behaving differently for you than for me.  I've put my .jar file on google Drive; try grabbing it and see how it works for you.

https://drive.google.com/file/d/16qsDAH03PRWonvS5812JLMVuCJyhU-6R/view?usp=sharing

**Comment by kjhambrick** [comment]
Joe --

I see the same thing in your OpenRocket-24.12.RC.01.jar

![Image](https://github.com/user-attachments/assets/d03a8c1e-0fcb-48c2-83e3-1e96df5e62f0)

But then I saw the [ ] Warning Check Box on the Plot Setup:

![Image](https://github.com/user-attachments/assets/d1181525-d01e-45d0-81fe-1de19c8c77f5)

I can 'clean up' the plots by disabling Show Warnings:

![Image](https://github.com/user-attachments/assets/c9849eaf-652b-48d5-8af9-a9f1ee1ae80b)

That'll work for me !

Thanks !

-- kjh

**Comment by JoePfeiffer** [comment]
I'm glad you've found a workaround that helps you, but there still seems to be a really screwy bug I need to track down....

You are re-running the simulations, aren't you?

**Comment by kjhambrick** [comment]
Joe --

Yes, I rerun the sims frequently.

Are you able to dupe the issue ?

Thanks for looking into this !

-- kjh

**Comment by JoePfeiffer** [comment]
> Are you able to dupe the issue ?

No, that's what has me so confused. When I ran an older version I saw the issue; when I run the .jar I sent you I don't. Could you put your build some place I can get it, so I can see if that duplicates it for me?

**Comment by kjhambrick** [comment]
I'll try to put it on google drive and let you know.

**Comment by JoePfeiffer** [comment]
Same thing running yours as running mine -- I open the .ork, plot the first sim, get a million supersonic warnings. Run the sim, plot again, I just get one warning when it first goes supersonic. I'm baffled.

**Comment by kjhambrick** [comment]
That's weird, Joe.

I can live with unchecking the [ ] Warnings Check Box

Thanks for all the time you spent helping me with this.

-- kjh

**Comment by SiboVG** [comment]
I can replicate this issue on the latest unstable:

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/5638987a-eff9-45d5-9f9b-54ca1a882415" />

However, rerunning the sim restores normal behavior:

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/4973752c-d721-4a6b-96a8-6f97fa70db4f" />

When I then save the .ork and re-open it, I again have normal behavior (only a few warnings).

So, is this still a bug? I think the .ork was saved in a version of OR that had the original bug, but it appears that it's fixed in the latest unstable.

**Comment by JoePfeiffer** [comment]
> So, is this still a bug? I think the .ork was saved in a version of OR that had the original bug, but it appears that it's fixed in the latest unstable.

I'm seeing the same behavior you are, and I don't understand why the user who reported the original bug is still seeing it.
