### ISSUE TITLE
[Bug] Unable to open file

### ISSUE THREAD

**Issue by ShootingStars76** [openrocket/openrocket#2800]
### Describe the bug

Have been working on a goofy rocket kinda as a meme project and was working on it for several days so have closed it / opened it several times. One day I tried to open it and it refused too and threw an error. After i clicked OK openrocket would then open but no file would be loaded. 

### To Reproduce

1. Open file 
2. Throws error with long bug code 
3. Try again same thing happens 
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*

![Image](https://github.com/user-attachments/assets/83647bac-48a8-4d89-9246-30757ff5d64f)

#### .ork file:

*(drag-and-drop the file here as a .zip file)*
[3in to 54mm 2 stage.zip](https://github.com/user-attachments/files/20146831/3in.to.54mm.2.stage.zip)

### OpenRocket version

24.12.RC.01

### What platform are you running on?

Windows

**Comment by senft-research** [comment]
This issue is related to #2777, with the root cause being identified, and is actively being worked on.

**Comment by JoePfeiffer** [comment]
Thank you for your report -- this is a duplicate of #2777

**Comment by ShootingStars76** [comment]
Welp I have done it again with the fixed file they gave me in the OpenRocket discord. All I changed was the booster motor and the launch site elevation (between balls and SLV). 

![Image](https://github.com/user-attachments/assets/b34b314c-be84-4ad3-9a69-ec72153cdc68)

[rocketFIX.zip](https://github.com/user-attachments/files/20150094/rocketFIX.zip)

**Comment by senft-research** [comment]
To add clarity, this is happening because you are changing your model, but then not updating your simulations. 

The issue I believe is the root cause is that the simulations that are "out of date" are saving warnings / messages / events that no longer exists / components that no longer exist (depends on exactly what the message was before update). 

The easiest way to prevent this (temporarily as the issue is resolved) is to always update / run your simulations after updating the model. 

The root cause of this issue (and the aforementioned #2777) is being worked on.

**Comment by JoePfeiffer** [comment]
> To add clarity, this is happening because you are changing your model, but then not updating your simulations.
> 
> The issue I believe is the root cause is that the simulations that are "out of date" are saving warnings / messages / events that no longer exists / components that no longer exist (depends on exactly what the message was before update).
> 
> The easiest way to prevent this (temporarily as the issue is resolved) is to always update / run your simulations after updating the model.
> 
> The root cause of this issue (and the aforementioned [#2777](https://github.com/openrocket/openrocket/issues/2777)) is being worked on.

This  is triggered slightly differently than #2777 -- it actually inserts a problematic event when the sim is rerun (that's why I reopened this issue).

**Comment by JoePfeiffer** [comment]
> Edit: just as i posted this it looks like the issue has been band aided for now (just included a parachute) but ill leave this up so you have more to work with if needed

Yes, it's been band-aided but not fixed. Please don't close this issue.
